[skip ci]update python example
antgroup/vsag pull request #152
Opened 2024-11-20 09:33 UTC by wxyucs

2024-11-20 16:17 UTC, jiaweizone approved these changes
LGTM

2024-11-27 06:57 UTC, LHT129 requested changes

2024-11-27 06:57 UTC, LHT129 commented on .gitignore
> +*.index
empty line

2024-11-27 12:01 UTC, wxyucs commented on .gitignore
> +*.index
fixed

2024-11-28 12:51 UTC, LHT129 approved these changes
LGTM

2024-11-29 02:57 UTC, merged