support in-place update operation for hnsw
antgroup/vsag pull request #196
Opened 2024-12-09 12:02 UTC by ShawnShawnYou

* support in-place update operation for hnsw

2024-12-16 08:02 UTC, inabao commented on tests/test_index_old.cpp
> +TEST_CASE("update vectors from the index", "[ft][index]") {
add thread-safe testing for hnsw

2024-12-17 09:09 UTC, ShawnShawnYou commented on tests/test_index_old.cpp
> +TEST_CASE("update vectors from the index", "[ft][index]") {
done

2024-12-23 08:47 UTC, inabao approved these changes
LGTM

2024-12-23 09:00 UTC, LHT129 requested changes

2024-12-23 09:00 UTC, LHT129 commented on tests/test_index_old.cpp
> +TEST_CASE("update id and vectors from the index", "[ft][index]") {
use new index test template for new interface functest

2024-12-23 09:00 UTC, LHT129 commented on include/vsag/index.h
> +    /**
add new feature on feature.h?

2024-12-23 09:00 UTC, LHT129 commented on tests/test_multi_thread.cpp
> +        update_id_results.push_back(
use new multithread test for update test

2024-12-23 09:00 UTC, LHT129 commented on include/vsag/index.h
> +     */
what is difference between `return false` and `error`

2024-12-23 09:00 UTC, LHT129 commented on src/algorithm/hnswlib/hnswalg.cpp
> +        normalizeVector(data_point, normalize_data);
need allocator?

2024-12-23 09:00 UTC, LHT129 commented on src/algorithm/hnswlib/hnswalg.cpp
> +        memcpy(getDataByInternalId(internal_id), data_point, data_size_);
why use data_point rathe than normalize_data

2024-12-23 09:58 UTC, jiaweizone commented on include/vsag/index.h
> +    UpdateId(int64_t old_id, int64_t new_id) {
Why need update id ?

2024-12-23 10:01 UTC, jiaweizone commented on src/algorithm/hnswlib/hnswalg.cpp
> +        internal_id = iter->second;
merge internal_id define to here
`InnerIdType internal_id = iter->second;`

2024-12-23 10:09 UTC, jiaweizone commented on src/algorithm/hnswlib/hnswalg.cpp
> +        normalizeVector(data_point, normalize_data);
minor: Why `normalizeVector` need change input param `data_point` ?
This update behavior means the `data_point` pointer memory life cycle changed

2024-12-23 10:13 UTC, jiaweizone commented on src/algorithm/hnswlib/hnswalg.cpp
> +        throw std::runtime_error("no label in HNSW");
minor: add the label id content to error message ?

2024-12-23 10:17 UTC, jiaweizone commented on src/index/hnsw.cpp
> +        std::unique_lock lock(rw_mutex_);
the lock is not necessary ？

2024-12-23 10:19 UTC, jiaweizone commented on src/index/hnsw.cpp
> +HNSW::update_vector(int64_t id, const DatasetPtr& new_base, bool need_fine_tune) {
`need_fine_tune` not use ?

2024-12-24 08:00 UTC, ShawnShawnYou commented on src/index/hnsw.cpp
> +HNSW::update_vector(int64_t id, const DatasetPtr& new_base, bool need_fine_tune) {
Remain it in the interface for further optimization ? (e.g., when distance is greater than specific threshold, we need to fine tune the graph structure)

2024-12-24 08:00 UTC, ShawnShawnYou commented on src/index/hnsw.cpp
> +        std::unique_lock lock(rw_mutex_);
done

2024-12-24 08:00 UTC, ShawnShawnYou commented on src/algorithm/hnswlib/hnswalg.cpp
> +        throw std::runtime_error("no label in HNSW");
done

2024-12-24 08:00 UTC, ShawnShawnYou commented on src/algorithm/hnswlib/hnswalg.cpp
> +        internal_id = iter->second;
done

2024-12-24 08:00 UTC, ShawnShawnYou commented on include/vsag/index.h
> +    UpdateId(int64_t old_id, int64_t new_id) {
For some cases, the users may only want to update the id or vector of a base point.  Then we need to provide two functions to provide flexibility.

2024-12-24 08:00 UTC, ShawnShawnYou commented on include/vsag/index.h
> +     */
`error` means un-supported index type or config conflicts. `false` means update failed.

2024-12-24 08:00 UTC, ShawnShawnYou commented on include/vsag/index.h
> +    /**
done

2024-12-24 08:00 UTC, ShawnShawnYou commented on tests/test_index_old.cpp
> +TEST_CASE("update id and vectors from the index", "[ft][index]") {
done

2024-12-24 08:01 UTC, ShawnShawnYou commented on tests/test_multi_thread.cpp
> +        update_id_results.push_back(
remains for next PR?

2024-12-24 08:03 UTC, ShawnShawnYou commented on src/algorithm/hnswlib/hnswalg.cpp
> +        normalizeVector(data_point, normalize_data);
this usage is align with `addPoint`, can be fixed in other PR

2024-12-24 08:03 UTC, ShawnShawnYou commented on src/algorithm/hnswlib/hnswalg.cpp
> +        memcpy(getDataByInternalId(internal_id), data_point, data_size_);
this usage is align with `addPoint`, can be fixed in other PR

2024-12-24 08:03 UTC, ShawnShawnYou commented on src/algorithm/hnswlib/hnswalg.cpp
> +        normalizeVector(data_point, normalize_data);
this usage is align with `addPoint`, can be fixed in other PR?

2024-12-24 09:18 UTC, jiaweizone commented on src/algorithm/hnswlib/hnswalg.cpp
> +        normalizeVector(data_point, normalize_data);
Ok, fix in next PR

2024-12-24 09:18 UTC, jiaweizone commented on src/index/hnsw.cpp
> +HNSW::update_vector(int64_t id, const DatasetPtr& new_base, bool need_fine_tune) {
Add TODO

2024-12-24 09:54 UTC, ShawnShawnYou commented on src/index/hnsw.cpp
> +HNSW::update_vector(int64_t id, const DatasetPtr& new_base, bool need_fine_tune) {
done

2024-12-25 06:40 UTC, jiaweizone approved these changes
LGTM

2024-12-26 02:09 UTC, LHT129 approved these changes
LGTM

2024-12-26 02:24 UTC, merged