implement the interfaces for add, knnsearch, serialize in pyramid
antgroup/vsag pull request #231
Opened 2024-12-18 09:41 UTC by inabao

#166

2024-12-23 07:53 UTC, LHT129 requested changes

2024-12-23 07:53 UTC, LHT129 commented on src/index/pyramid_zparameters.cpp
> +}  // namespace vsag
format

2024-12-23 07:53 UTC, LHT129 commented on src/index/pyramid.cpp
> +        auto newReader = std::shared_ptr<SubReader>(new SubReader(reader, offset, binarySize));
make shared

2024-12-23 07:53 UTC, LHT129 commented on src/index/pyramid.h
> +#include "../safe_allocator.h"
#include "safe_allocator.h"

2024-12-23 07:53 UTC, LHT129 commented on src/index/pyramid.h
> +    Pyramid(PyramidParameters pyramid_param, const IndexCommonParam commom_param)
ref

2024-12-24 10:28 UTC, inabao commented on src/index/pyramid.cpp
> +        auto newReader = std::shared_ptr<SubReader>(new SubReader(reader, offset, binarySize));
done

2024-12-24 10:28 UTC, inabao commented on src/index/pyramid_zparameters.cpp
> +}  // namespace vsag
done

2024-12-24 10:28 UTC, inabao commented on src/index/pyramid.h
> +#include "../safe_allocator.h"
done

2024-12-24 10:28 UTC, inabao commented on src/index/pyramid.h
> +    Pyramid(PyramidParameters pyramid_param, const IndexCommonParam commom_param)
done

2024-12-25 06:13 UTC, LHT129 approved these changes
LGTM

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    size_t totalSize = 0;
totalSize -> total_size

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +binaryset_to_binary(const BinarySet binarySet) {
binarySet -> binary_set

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        size_t keySize = key.size();
keySize -> key_size

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    BinarySet binarySet;
binarySet -> binary_set

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        size_t keySize;
keySize -> key_size

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        memcpy(&keySize, binary.data.get() + offset, sizeof(size_t));
ditto

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        Binary newBinary;
newBinary -> new_binary

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        size_t binarySize;
binarySize -> binary_size

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    ReaderSet readerSet;
reader_set

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        size_t keySize;
key_size

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        size_t binarySize;
binary_size

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        auto newReader = std::make_shared<SubReader>(reader, offset, binarySize);
new_reader

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    std::string lastToken = str.substr(start);
lastToken -> last_token

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +constexpr static const char PART_SLASH = '/';
move to file head ?

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +split(const std::string& str, char delimiter) {
can use std lib or boost lib `split` implement ?

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        std::shared_ptr<IndexNode> node = indexes_.at(result[0]);
minor: here can reduce one find cost

2025-01-01 17:14 UTC, jiaweizone commented on src/index/pyramid.cpp
> +            node = node->children.at(result[j]);
ditto

2025-01-02 02:57 UTC, inabao commented on src/index/pyramid.cpp
> +    size_t totalSize = 0;
done

2025-01-02 02:57 UTC, inabao commented on src/index/pyramid.cpp
> +binaryset_to_binary(const BinarySet binarySet) {
done

2025-01-02 02:58 UTC, inabao commented on src/index/pyramid.cpp
> +        size_t keySize = key.size();
done

2025-01-02 02:58 UTC, inabao commented on src/index/pyramid.cpp
> +    BinarySet binarySet;
done

2025-01-02 02:58 UTC, inabao commented on src/index/pyramid.cpp
> +        size_t keySize;
done

2025-01-02 02:58 UTC, inabao commented on src/index/pyramid.cpp
> +        memcpy(&keySize, binary.data.get() + offset, sizeof(size_t));
done

2025-01-02 02:58 UTC, inabao commented on src/index/pyramid.cpp
> +        Binary newBinary;
done

2025-01-02 02:58 UTC, inabao commented on src/index/pyramid.cpp
> +        size_t binarySize;
done

2025-01-02 02:58 UTC, inabao commented on src/index/pyramid.cpp
> +    ReaderSet readerSet;
done

2025-01-02 02:58 UTC, inabao commented on src/index/pyramid.cpp
> +        size_t keySize;
done

2025-01-02 02:59 UTC, inabao commented on src/index/pyramid.cpp
> +        size_t binarySize;
done

2025-01-02 02:59 UTC, inabao commented on src/index/pyramid.cpp
> +        auto newReader = std::make_shared<SubReader>(reader, offset, binarySize);
done

2025-01-02 02:59 UTC, inabao commented on src/index/pyramid.cpp
> +    std::string lastToken = str.substr(start);
done

2025-01-02 03:03 UTC, inabao commented on src/index/pyramid.cpp
> +constexpr static const char PART_SLASH = '/';
done

2025-01-02 03:07 UTC, inabao commented on src/index/pyramid.cpp
> +split(const std::string& str, char delimiter) {
It seems that there is no split function in the standard library. Currently, vsag has no dependencies on Boost, so it would be a bit excessive to introduce Boost just for the split function.

2025-01-02 03:26 UTC, inabao commented on src/index/pyramid.cpp
> +        std::shared_ptr<IndexNode> node = indexes_.at(result[0]);
done

2025-01-02 03:26 UTC, inabao commented on src/index/pyramid.cpp
> +            node = node->children.at(result[j]);
done

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +split(const std::string& str, char delimiter) {
OK，can move to common utils file

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +        auto result = split(current_path, PART_SLASH);
result -> path_slices ?

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +split(const std::string& str, char delimiter) {
Please reference high performance implement (eg. boost / absl)

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    auto parsed_path = split(current_path, PART_SLASH);
parsed_path -> path_slices ?

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    std::shared_ptr<IndexNode> root = indexes_.at(parsed_path[0]);
minor: reduce cost

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    std::shared_ptr<IndexNode> root = indexes_.at(parsed_path[0]);
minor: reduce cost

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    std::shared_ptr<IndexNode> root = indexes_.at(parsed_path[0]);
minor: reduce cost

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +    std::shared_ptr<IndexNode> root = indexes_.at(parsed_path[0]);
minor: reduce cost

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +                for (int i = 0; i < r->GetDim(); ++i) {
r->GetDim() ?
is r->GetElements() ?

2025-01-02 18:25 UTC, jiaweizone commented on src/index/pyramid.cpp
> +                candidate_indexes.emplace_back(item.second);
do search for all sub tree ?

2025-01-03 08:37 UTC, inabao commented on src/index/pyramid.cpp
> +        auto result = split(current_path, PART_SLASH);
done

2025-01-03 08:38 UTC, inabao commented on src/index/pyramid.cpp
> +    auto parsed_path = split(current_path, PART_SLASH);
done

2025-01-03 08:38 UTC, inabao commented on src/index/pyramid.cpp
> +    std::shared_ptr<IndexNode> root = indexes_.at(parsed_path[0]);
done

2025-01-03 08:40 UTC, inabao commented on src/index/pyramid.cpp
> +    std::shared_ptr<IndexNode> root = indexes_.at(parsed_path[0]);
done

2025-01-03 08:40 UTC, inabao commented on src/index/pyramid.cpp
> +    std::shared_ptr<IndexNode> root = indexes_.at(parsed_path[0]);
done

2025-01-03 08:40 UTC, inabao commented on src/index/pyramid.cpp
> +    std::shared_ptr<IndexNode> root = indexes_.at(parsed_path[0]);
done

2025-01-03 08:41 UTC, inabao commented on src/index/pyramid.cpp
> +                for (int i = 0; i < r->GetDim(); ++i) {
r->GetDim() denotes the number of the results for single query. r->GetElements() denotes the number of queries

2025-01-03 08:43 UTC, inabao commented on src/index/pyramid.cpp
> +                candidate_indexes.emplace_back(item.second);
If a node has an index, then its child nodes will not be searched.

2025-01-06 11:37 UTC, jiaweizone commented on src/default_allocator.h
> +        //#ifndef NDEBUG
remove unused code

2025-01-06 11:37 UTC, jiaweizone commented on src/index/pyramid.cpp
> +                for (int i = 0; i < r->GetDim(); ++i) {
reminder: Update in next PR

2025-01-06 11:48 UTC, inabao commented on src/default_allocator.h
> +        //#ifndef NDEBUG
This part is the code with incorrect comments, which has now been restored.

2025-01-06 12:00 UTC, jiaweizone commented on src/index/pyramid.cpp
> +                candidate_indexes.emplace_back(item.second);
It's necessary to introduce retrieval logic that recursively flows from higher layers to lower layers.

2025-01-09 13:06 UTC, jiaweizone approved these changes
some issues will fix in next PR

2025-01-09 13:59 UTC, merged