support filter in test performance
antgroup/vsag pull request #81
Opened 2024-10-22 11:14 UTC by inabao

2024-10-22 15:08 UTC, wxyucs commented on tests/performance/test_performance.cpp
> -    set_level(level::off);
what is the reason to remove this line?

2024-10-22 16:36 UTC, jiaweizone commented on tests/performance/test_performance.cpp
> +        int64_t total = 100;
Why change to constant value `100` ?

2024-10-23 04:00 UTC, inabao commented on tests/performance/test_performance.cpp
> +        int64_t total = 100;
i has restored it.

2024-10-23 04:01 UTC, inabao commented on tests/performance/test_performance.cpp
> -    set_level(level::off);
i has restored it.

2024-10-31 06:59 UTC, wxyucs requested changes

2024-10-31 06:59 UTC, wxyucs commented on tests/performance/test_performance.cpp
> +        }
add comments about why separate code into two scopes

2024-10-31 07:28 UTC, inabao commented on tests/performance/test_performance.cpp
> +        }
revised

2024-10-31 08:06 UTC, wxyucs approved these changes
lgtm

2024-11-01 02:51 UTC, jiaweizone approved these changes
LGTM

2024-11-01 02:52 UTC, merged